<a href="https://colab.research.google.com/github/gathosan012/AI_Exercise/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def create_array():

    arr = np.arange(5, 905, 10)
    return arr

In [6]:
import numpy as np

def create_array_from_range_list():

    python_range = range(5, 905, 10)
    python_list = list(python_range)
    arr = np.array(python_list)
    return arr


In [7]:
import numpy as np
import string

def create_uppercase_array():

    # string.ascii_uppercase provides a string 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    uppercase_letters_string = string.ascii_uppercase

    # Convert the string to a list of individual characters
    uppercase_letters_list = list(uppercase_letters_string)

    # Create a NumPy array from the list
    arr = np.array(uppercase_letters_list)
    return arr

In [8]:
import numpy as np

def create_zeros_and_ones_arrays():

    zeros_array = np.zeros(10)
    ones_array = np.ones(6)
    return zeros_array, ones_array

In [9]:
import numpy as np

def print_third_column(input_array):
    input_array = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
    if input_array.ndim != 2:
        print("Input array is not 2-dimensional.")
        return

    if input_array.shape[1] < 3:
        print("Input array does not have a third column.")
        return

    print(input_array[:, 2])

In [10]:
import numpy as np

def create_zeros_int64_array():

    arr = np.zeros((3, 4), dtype=np.int64)
    return arr

In [12]:
import numpy as np

def split_array_into_three(input_array):
    input_array = np.arange(7, 34, 1).reshape(9, 3)
    if input_array.size % 3 != 0:
        print("Warning: The array cannot be split into 3 exactly equal-sized sub-arrays.")
        return np.array_split(input_array, 3)
    else:
        return np.split(input_array, 3)

In [13]:
import numpy as np

def get_last_two_elements_from_first_two_rows(input_array):
    input_array = np.arange(1, 13, 1).reshape(3, 4)

    # The slicing [0:2, -2:] means:
    # 0:2 -> rows from index 0 up to (but not including) index 2 (i.e., row 0 and row 1)
    # -2: -> columns from the second to last up to the end (i.e., the last two columns)
    result = input_array[0:2, -2:]
    return result

In [14]:
import numpy as np

def count_elements_greater_than_five(input_array):

    count = np.sum(input_array > 5)
    return count

In [21]:
import numpy as np

def delete_and_insert_column(arr, new_column_data):

    if arr.ndim < 2:
        raise ValueError("Input array must be at least 2-dimensional.")

    # Ensure new_column_data is handled correctly for insertion as a single column
    if new_column_data.ndim == 0:
        new_column_to_insert = np.array([new_column_data])
    elif new_column_data.ndim == 2:
        if new_column_data.shape[0] == 1:
            new_column_to_insert = new_column_data.flatten()
        elif new_column_data.shape[1] == 1:
            new_column_to_insert = new_column_data.flatten()
        else:
            raise ValueError("New column must be 1-dimensional or a 2-dimensional array with a single column (e.g., (N, 1) shape).")
    else: # new_column_data.ndim == 1 (already a 1D array)
        new_column_to_insert = new_column_data


    if arr.shape[0] != len(new_column_to_insert):
        raise ValueError(f"The number of rows in the array ({arr.shape[0]}) must match the length of the new column ({len(new_column_to_insert)}).")

    modified_arr = np.delete(arr, 1, axis=1)

    final_arr = np.insert(modified_arr, 1, new_column_to_insert, axis=1)

    return final_arr

# Define the input arrays outside the function
input_array = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])

result_array = delete_and_insert_column(input_array, insert_data)

# Print the result
print(result_array)


[[34 37 33]
 [82 37 32]
 [59 37 10]]


In [17]:
import numpy as np

def compute_euclidean_distance_and_append(input_array):

    if input_array.ndim != 2:
        raise ValueError("Input array must be 2-dimensional.")
    if input_array.shape[0] < 2:
        return np.hstack((input_array, np.zeros((input_array.shape[0], 1))))


    distances = [0.0]

    for i in range(1, input_array.shape[0]):
        point1 = input_array[i-1]
        point2 = input_array[i]

        # Euclidean distance formula
        distance = np.sqrt(np.sum((point2 - point1)**2))
        distances.append(distance)

    distances_array = np.array(distances).reshape(-1, 1)

    result_array = np.hstack((input_array, distances_array))

    return result_array

input_data = np.array([[1, 2], [4, 6], [7, 8], [10, 10]])

output_array = compute_euclidean_distance_and_append(input_data)

print(output_array)

[[ 1.          2.          0.        ]
 [ 4.          6.          5.        ]
 [ 7.          8.          3.60555128]
 [10.         10.          3.60555128]]


In [22]:
import numpy as np

def remove_consecutive_duplicates(input_array):

    if input_array.size == 0:
        return input_array

    unique_rows = [input_array[0]]

    for i in range(1, input_array.shape[0]):
        if not np.array_equal(input_array[i], unique_rows[-1]):
            unique_rows.append(input_array[i])

    return np.array(unique_rows)

input_data = np.array([[1, 1], [2, 1], [3, 3], [3, 3], [2, 1], [1, 1]])

# Call the function
output_array = remove_consecutive_duplicates(input_data)

print(output_array)

[[1 1]
 [2 1]
 [3 3]
 [2 1]
 [1 1]]


In [24]:
import numpy as np

def normalize_strokes(input_array):

    if input_array.ndim != 2:
        raise ValueError("Input array must be 2-dimensional.")
    if input_array.shape[0] == 0:
        return input_array # Return empty array if input is empty

    column_means = np.mean(input_array, axis=0)

    column_stds = np.std(input_array, axis=0)

    safe_column_stds = np.where(column_stds == 0, 1, column_stds)

    normalized_array = (input_array - column_means) / safe_column_stds

    return normalized_array

# Provided input array
input_data = np.array([[10, 20, 30], [15, 24, 33], [8, 18, 29], [14, 22, 32]])

output_array = normalize_strokes(input_data)

print(output_array)

[[-0.61159284 -0.4472136  -0.63245553]
 [ 1.13581527  1.34164079  1.26491106]
 [-1.31055608 -1.34164079 -1.26491106]
 [ 0.78633365  0.4472136   0.63245553]]


In [25]:
import numpy as np

def normalize_strokes(input_array):

    if input_array.ndim != 2:
        raise ValueError("Input array must be 2-dimensional.")
    if input_array.shape[0] == 0:
        return input_array


    column_means = np.mean(input_array, axis=0)

    column_stds = np.std(input_array, axis=0)

    safe_column_stds = np.where(column_stds == 0, 1, column_stds)

    normalized_array = (input_array - column_means) / safe_column_stds

    return normalized_array

input_data = np.array([[10, 20, 30], [15, 24, 33], [8, 18, 29], [14, 22, 32]])

output_array = normalize_strokes(input_data)

print(output_array)

[[-0.61159284 -0.4472136  -0.63245553]
 [ 1.13581527  1.34164079  1.26491106]
 [-1.31055608 -1.34164079 -1.26491106]
 [ 0.78633365  0.4472136   0.63245553]]


In [26]:
import numpy as np

def extract_unique_characters(input_array):

    if input_array.dtype.kind not in 'USV':
        raise ValueError("Input array must contain strings.")

    unique_chars_set = set()

    for s in input_array:
        for char in s:
            unique_chars_set.add(char)

    sorted_unique_chars = sorted(list(unique_chars_set))

    return np.array(sorted_unique_chars)

input_data = np.array(["hello", "world", "numpy", "rocks"])

output_array = extract_unique_characters(input_data)

print(output_array)

['c' 'd' 'e' 'h' 'k' 'l' 'm' 'n' 'o' 'p' 'r' 's' 'u' 'w' 'y']


In [27]:
import numpy as np

def map_unique_chars_to_index(input_array):

    unique_chars = np.unique(input_array)

    char_to_index_map = {char: index for index, char in enumerate(unique_chars)}

    return char_to_index_map

input_data = np.array(["a", "b", "c", "d", "a", "c", "e"])

output_dictionary = map_unique_chars_to_index(input_data)

print(output_dictionary)

{np.str_('a'): 0, np.str_('b'): 1, np.str_('c'): 2, np.str_('d'): 3, np.str_('e'): 4}


In [29]:
import numpy as np

def convert_traces_to_single_array(list_of_traces):

    if not list_of_traces:
        return np.array([])

    single_array = np.vstack(list_of_traces)

    return single_array

input_data = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8], [9, 10]])]

output_array = convert_traces_to_single_array(input_data)

print(output_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [30]:
import numpy as np

def return_simple_array():

    return np.array([1, 2, 3])

In [31]:
import numpy as np

def extract_nonzero_differences(input_array):

    if input_array.size == 0:
        return input_array # Return empty array if input is empty

    nonzero_rows_mask = np.any(input_array != 0, axis=1)

    extracted_array = input_array[nonzero_rows_mask]

    return extracted_array

input_data = np.array([[3, 4], [0, 0], [-2, 1]])

output_array = extract_nonzero_differences(input_data)

print(output_array)

input_all_zeros = np.array([[0, 0], [0, 0]])
output_all_zeros = extract_nonzero_differences(input_all_zeros)
print(output_all_zeros)

input_all_nonzero = np.array([[1, 2], [3, 4]])
output_all_nonzero = extract_nonzero_differences(input_all_nonzero)
print(output_all_nonzero)

[[ 3  4]
 [-2  1]]
[]
[[1 2]
 [3 4]]


In [32]:
import numpy as np

def return_simple_array():

    return np.array([1, 2, 3])